<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>QuizMaster - Quziy</title>
        <link rel="shortcut icon" href="./image/favicon.png" type="image/x-icon">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
        <link rel="stylesheet" href="../styles/style_global.css">
        <link rel="stylesheet" href="../styles/style_cookies.css">
    </head>
    <body>
        <section class="document">
                <?php 
                    require_once('./elements/header.php');
                ?>
                <section class="document-body">
                    <!-- Rules are generated by chatGPT -->
                    <main>
                        <h1 class="cookie-text">Polityka Cookies</h1>
                        <div class="cookie-text">
                            <h2 class="cookie-text">1. Wprowadzenie</h2>
                            <p>Nasza strona internetowa używa plików cookies, aby poprawić jej funkcjonalność oraz zapewnić lepsze wrażenia z użytkowania. Pliki cookies są małymi plikami tekstowymi, które są przechowywane na Twoim urządzeniu, gdy odwiedzasz naszą stronę. Niniejsza polityka wyjaśnia, czym są pliki cookies, jakie rodzaje cookies stosujemy, jak ich używamy i jak możesz nimi zarządzać.</p>

                            <h2 class="cookie-text">2. Czym są pliki cookies?</h2>
                            <p>Pliki cookies to małe pliki tekstowe umieszczane na Twoim urządzeniu (komputerze, smartfonie, tablecie itp.), które umożliwiają stronom internetowym zapamiętywanie Twoich preferencji i działań przez określony czas. Pliki cookies pozwalają stronie rozpoznać Twoje urządzenie i ułatwić korzystanie z niej, np. poprzez zapamiętywanie Twoich preferencji lub loginu.</p>

                            <h2 class="cookie-text">3. Jakie pliki cookies używamy?</h2>
                            <p>Używamy różnych rodzajów plików cookies, aby zapewnić optymalne działanie naszej strony:</p>
                            <ol>
                                <li><strong>Cookies funkcjonalne:</strong> Te pliki cookies są niezbędne do zapewnienia podstawowych funkcji naszej strony, takich jak logowanie, zarządzanie sesją oraz zapamiętywanie ustawień użytkownika. Bez tych plików cookies strona może nie działać prawidłowo.</li>
                                <li><strong>Cookies analityczne:</strong> Pomagają nam w analizowaniu, jak odwiedzający korzystają z naszej strony. Dzięki nim możemy śledzić, które strony są najczęściej odwiedzane, jakie funkcje są używane oraz jakie są źródła ruchu. Pomaga nam to w doskonaleniu naszej strony i dostosowywaniu jej do potrzeb użytkowników.</li>
                                <li><strong>Cookies reklamowe:</strong> Służą do dostosowywania reklam, które widzisz, do Twoich zainteresowań. Dzięki nim możemy prezentować Ci bardziej trafne i interesujące reklamy, bazując na Twoich wcześniejszych odwiedzinach strony.</li>
                                <li><strong>Cookies zewnętrzne:</strong> Nasza strona może korzystać z plików cookies dostarczanych przez strony trzecie, takie jak usługi analityczne (np. Google Analytics) czy media społecznościowe (np. Facebook, Twitter). Pliki cookies tych dostawców mogą mieć różne cele i są zarządzane przez polityki prywatności tych firm.</li>
                            </ol>

                            <h2 class="cookie-text">4. Jak zarządzać plikami cookies?</h2>
                            <p>Masz prawo do zarządzania plikami cookies przechowywanymi na Twoim urządzeniu. Możesz kontrolować i/lub usuwać pliki cookies według własnego uznania. Większość przeglądarek internetowych pozwala na:</p>
                            <ol>
                                <li>Akceptowanie plików cookies.</li>
                                <li>Blokowanie plików cookies.</li>
                                <li>Usuwanie plików cookies.</li>
                                <li>Otrzymywanie powiadomień o plikach cookies.</li>
                            </ol>
                            <p>Informacje na temat zarządzania plikami cookies w poszczególnych przeglądarkach znajdziesz w dokumentacji lub ustawieniach przeglądarki. Warto pamiętać, że zmiana ustawień plików cookies może wpłynąć na działanie naszej strony i ograniczyć jej funkcjonalność.</p>

                            <h2 class="cookie-text">5. Szczegółowe informacje o używanych plikach cookies</h2>
                            <p>Poniżej znajduje się lista plików cookies, które mogą być używane na naszej stronie:</p>
                            <ol>
                                <li><strong>Session Cookies:</strong> Te pliki cookies są tymczasowe i są usuwane, gdy zamykasz przeglądarkę. Służą do przechowywania informacji, które są potrzebne podczas jednej sesji przeglądania.</li>
                                <li><strong>Persistent Cookies:</strong> Te pliki cookies pozostają na Twoim urządzeniu przez określony czas lub do momentu ich usunięcia. Są używane do przechowywania preferencji użytkownika na dłuższy czas.</li>
                                <li><strong>First-party Cookies:</strong> Są to pliki cookies umieszczane bezpośrednio przez naszą stronę internetową i są używane tylko przez naszą stronę.</li>
                                <li><strong>Third-party Cookies:</strong> Są to pliki cookies umieszczane przez strony trzecie (np. dostawców usług analitycznych, reklamowych). Te pliki cookies mogą być używane przez strony trzecie do śledzenia Twoich działań online.</li>
                            </ol>

                            <h2 class="cookie-text">6. Bezpieczeństwo plików cookies</h2>
                            <p>Pliki cookies nie stanowią zagrożenia dla Twojego komputera. Nie mogą przenosić wirusów ani złośliwego oprogramowania. Jednakże, niektóre pliki cookies mogą być wykorzystywane do śledzenia Twojej aktywności w sieci, co może budzić obawy dotyczące prywatności. Dlatego zalecamy zarządzanie plikami cookies zgodnie z Twoimi preferencjami.</p>

                            <h2 class="cookie-text">7. Zmiany w Polityce Cookies</h2>
                            <p>Możemy od czasu do czasu aktualizować naszą Politykę Cookies. Wszelkie zmiany będą publikowane na tej stronie. O wszelkich istotnych zmianach poinformujemy użytkowników poprzez odpowiednie komunikaty na stronie lub inne dostępne środki. Data ostatniej aktualizacji będzie wskazana na początku dokumentu.</p>

                            <h2 class="cookie-text">8. Kontakt</h2>
                            <p>Jeśli masz pytania dotyczące naszej Polityki Cookies lub jakiegokolwiek aspektu korzystania z plików cookies na naszej stronie, prosimy o kontakt za pośrednictwem formularza kontaktowego dostępnego na stronie lub poprzez e-mail na adres: <a href="mailto:kontakt@twojastrona.pl">kontakt@twojastrona.pl</a>.</p>
                        </div>
                    </main>
                </section>
                <?php
                    require_once('./elements/footer.html');
                ?>
        </section>
    </body>
</html>