<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>QuizMaster - Quziy</title>
        <link rel="shortcut icon" href="./image/favicon.png" type="image/x-icon">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
        <link rel="stylesheet" href="../styles/style_global.css">
        <link rel="stylesheet" href="../styles/style_rules.css">
    </head>
    <body>
        <section class="document">
                <?php 
                    require_once('./elements/header.php');
                ?>
                <section class="document-body">
                    <!-- Rules are generated by chatGPT -->
                    <main>
                        <h1 class="rules-text">Regulamin Serwisu</h1>

                        <h2 class="rules-text">1. Wprowadzenie</h2>
                        <p class="rules-text">Witamy na naszej stronie z quizami. Niniejszy regulamin określa zasady korzystania z naszej witryny oraz usługi quizów. Korzystając z naszej strony, akceptujesz poniższe zasady i zobowiązujesz się ich przestrzegać.</p>

                        <h2 class="rules-text">2. Rejestracja i Konto</h2>
                        <h3 class="rules-text">2.1. Rejestracja</h3>
                        <p class="rules-text">Aby korzystać z pełnej funkcjonalności strony, użytkownik może zostać poproszony o rejestrację i założenie konta. Rejestracja jest dobrowolna, ale niezbędna do korzystania z niektórych funkcji.</p>
                        <h3 class="rules-text">2.2. Odpowiedzialność za Konto</h3>
                        <p class="rules-text">Użytkownik jest odpowiedzialny za utrzymanie poufności swojego loginu i hasła oraz za wszelkie działania, które mają miejsce na jego koncie. Zabrania się udostępniania danych logowania osobom trzecim.</p>
                        <h3 class="rules-text">2.3. Bezpieczeństwo</h3>
                        <p class="rules-text">Użytkownik zobowiązuje się do natychmiastowego powiadomienia nas o wszelkich nieautoryzowanych działaniach na swoim koncie oraz do aktualizowania swoich danych kontaktowych.</p>

                        <h2 class="rules-text">3. Korzystanie z Quizów</h2>
                        <h3 class="rules-text">3.1. Zasady Korzystania</h3>
                        <p class="rules-text">Użytkownicy mogą korzystać z quizów w celach rozrywkowych i edukacyjnych. Zabrania się używania strony do działań niezgodnych z prawem lub szkodliwych, w tym rozsyłania spamu czy wirusów.</p>
                        <h3 class="rules-text">3.2. Zakaz Oszustwa</h3>
                        <p class="rules-text">Użytkownicy zobowiązują się do uczciwego udziału w quizach i nie będą stosować żadnych oszukańczych metod, takich jak używanie botów lub oprogramowania wspomagającego.</p>
                        <h3 class="rules-text">3.3. Własność Treści</h3>
                        <p class="rules-text">Wszystkie treści zamieszczane przez użytkowników, takie jak pytania do quizów, są ich własnością intelektualną. Użytkownik udziela nam jednak licencji na ich wykorzystanie w ramach strony, w tym na publikację i promocję.</p>
                        <h3 class="rules-text">3.4. Moderacja Treści</h3>
                        <p class="rules-text">Zastrzegamy sobie prawo do moderowania treści w quizach, w tym do usuwania treści naruszających regulamin lub przepisy prawne.</p>

                        <h2 class="rules-text">4. Prawa Autorskie</h2>
                        <h3 class="rules-text">4.1. Własność Treści</h3>
                        <p class="rules-text">Cała zawartość strony, w tym teksty, obrazy, grafiki i inne materiały, jest objęta prawem autorskim i nie może być kopiowana ani wykorzystywana bez zgody właścicieli praw autorskich.</p>
                        <h3 class="rules-text">4.2. Zgłaszanie Naruszeń</h3>
                        <p class="rules-text">Użytkownicy mogą zgłaszać naruszenia praw autorskich zgodnie z procedurami opisanymi na stronie. Zastrzegamy sobie prawo do podejmowania działań w przypadku zgłoszenia naruszenia.</p>

                        <h2 class="rules-text">5. Ochrona Danych Osobowych</h2>
                        <h3 class="rules-text">5.1. Polityka Prywatności</h3>
                        <p class="rules-text">Twoje dane osobowe są chronione zgodnie z naszą Polityką Prywatności, która jest częścią niniejszego regulaminu. Polityka Prywatności opisuje, w jaki sposób gromadzimy, przechowujemy i wykorzystujemy Twoje dane osobowe.</p>
                        <h3 class="rules-text">5.2. Zgoda na Przetwarzanie</h3>
                        <p class="rules-text">Korzystając z naszej strony, wyrażasz zgodę na przetwarzanie danych osobowych zgodnie z Polityką Prywatności. Możesz w każdej chwili wycofać zgodę, kontaktując się z nami.</p>

                        <h2 class="rules-text">6. Zasady Postępowania</h2>
                        <h3 class="rules-text">6.1. Zabronione Działania</h3>
                        <p class="rules-text">Zabrania się publikowania treści, które są obraźliwe, nielegalne, szkodliwe, w tym treści dyskryminujących, nękających lub promujących przemoc.</p>
                        <h3 class="rules-text">6.2. Usuwanie Treści</h3>
                        <p class="rules-text">Zastrzegamy sobie prawo do usuwania treści, które naruszają regulamin, oraz do blokowania kont użytkowników, którzy łamią zasady. Usuwanie treści i blokowanie kont mogą być dokonywane bez wcześniejszego powiadomienia.</p>
                        <h3 class="rules-text">6.3. Reklamacje</h3>
                        <p class="rules-text">Wszelkie reklamacje dotyczące korzystania z serwisu należy zgłaszać za pośrednictwem formularza kontaktowego. Rozpatrujemy reklamacje w możliwie najkrótszym czasie i informujemy o podjętych działaniach.</p>

                        <h2 class="rules-text">7. Zmiany w Regulaminie</h2>
                        <h3 class="rules-text">7.1. Aktualizacje</h3>
                        <p class="rules-text">Zastrzegamy sobie prawo do wprowadzania zmian w regulaminie. Zmiany będą publikowane na stronie i obowiązują od momentu ich opublikowania. Regularnie sprawdzaj regulamin, aby być na bieżąco z ewentualnymi zmianami.</p>
                        <h3 class="rules-text">7.2. Akceptacja</h3>
                        <p class="rules-text">Kontynuowanie korzystania z naszej strony po wprowadzeniu zmian oznacza akceptację zaktualizowanego regulaminu. W przypadku braku akceptacji nowych warunków, użytkownik powinien zaprzestać korzystania z serwisu.</p>

                        <h2 class="rules-text">8. Postanowienia Końcowe</h2>
                        <h3 class="rules-text">8.1. Prawo Właściwe</h3>
                        <p class="rules-text">Regulamin podlega prawu obowiązującemu w kraju, w którym prowadzona jest strona. Wszelkie spory wynikłe w związku z korzystaniem z serwisu będą rozstrzygane przez sąd właściwy dla siedziby właściciela strony.</p>
                        <h3 class="rules-text">8.2. Kontakt</h3>
                        <p class="rules-text">W razie pytań dotyczących regulaminu, prosimy o kontakt za pośrednictwem formularza kontaktowego dostępnego na stronie lub na adres e-mail: kontakt@example.com.</p>
                        <h3 class="rules-text">8.3. Przekazywanie Praw i Obowiązków</h3>
                        <p class="rules-text">Zastrzegamy sobie prawo do przekazania naszych praw i obowiązków wynikających z niniejszego regulaminu innym podmiotom, pod warunkiem że zapewnimy, iż Twoje prawa będą chronione w takim samym zakresie.</p>
                        <h3 class="rules-text">8.4. Nieważność Postanowień</h3>
                        <p class="rules-text">Jeśli którekolwiek z postanowień regulaminu okaże się nieważne lub niewykonalne, pozostałe postanowienia pozostaną w mocy i będą w pełni obowiązywać.</p>
                    </main>
                </section>
                <?php
                    require_once('./elements/footer.html');
                ?>
        </section>
    </body>
</html>